/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as ProfileGalleryRouteImport } from './routes/profile/gallery'
import { Route as ProfileCategoriesRouteImport } from './routes/profile/categories'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGalleryRoute = ProfileGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileCategoriesRoute = ProfileCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof ProfileRouteRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/upload': typeof UploadRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/gallery': typeof ProfileGalleryRoute
}
export interface FileRoutesByTo {
  '/profile': typeof ProfileRouteRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/upload': typeof UploadRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/gallery': typeof ProfileGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/profile': typeof ProfileRouteRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/upload': typeof UploadRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/gallery': typeof ProfileGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/gallery'
    | '/upload'
    | '/profile/categories'
    | '/profile/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/gallery'
    | '/upload'
    | '/profile/categories'
    | '/profile/gallery'
  id:
    | '__root__'
    | '/profile'
    | '/gallery'
    | '/upload'
    | '/profile/categories'
    | '/profile/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/gallery': {
      id: '/profile/gallery'
      path: '/gallery'
      fullPath: '/profile/gallery'
      preLoaderRoute: typeof ProfileGalleryRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/categories': {
      id: '/profile/categories'
      path: '/categories'
      fullPath: '/profile/categories'
      preLoaderRoute: typeof ProfileCategoriesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileCategoriesRoute: typeof ProfileCategoriesRoute
  ProfileGalleryRoute: typeof ProfileGalleryRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileCategoriesRoute: ProfileCategoriesRoute,
  ProfileGalleryRoute: ProfileGalleryRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  GalleryRoute: GalleryRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
