/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as UserIdRouteRouteImport } from './routes/$userId/route'
import { Route as UserIdIndexRouteImport } from './routes/$userId/index'
import { Route as UserIdUploadRouteImport } from './routes/$userId/upload'
import { Route as UserIdProfileRouteRouteImport } from './routes/$userId/profile/route'
import { Route as UserIdProfileSettingsRouteImport } from './routes/$userId/profile/settings'
import { Route as UserIdProfileGalleryRouteImport } from './routes/$userId/profile/gallery'
import { Route as UserIdProfileAlbumsRouteImport } from './routes/$userId/profile/albums'
import { Route as UserIdAlbumAlbumIdRouteImport } from './routes/$userId/album/$albumId'

const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRouteRoute = UserIdRouteRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserIdRouteRoute,
} as any)
const UserIdUploadRoute = UserIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => UserIdRouteRoute,
} as any)
const UserIdProfileRouteRoute = UserIdProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserIdRouteRoute,
} as any)
const UserIdProfileSettingsRoute = UserIdProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserIdProfileRouteRoute,
} as any)
const UserIdProfileGalleryRoute = UserIdProfileGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => UserIdProfileRouteRoute,
} as any)
const UserIdProfileAlbumsRoute = UserIdProfileAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => UserIdProfileRouteRoute,
} as any)
const UserIdAlbumAlbumIdRoute = UserIdAlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => UserIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$userId': typeof UserIdRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/$userId/profile': typeof UserIdProfileRouteRouteWithChildren
  '/$userId/upload': typeof UserIdUploadRoute
  '/$userId/': typeof UserIdIndexRoute
  '/$userId/album/$albumId': typeof UserIdAlbumAlbumIdRoute
  '/$userId/profile/albums': typeof UserIdProfileAlbumsRoute
  '/$userId/profile/gallery': typeof UserIdProfileGalleryRoute
  '/$userId/profile/settings': typeof UserIdProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/signIn': typeof SignInRoute
  '/$userId/profile': typeof UserIdProfileRouteRouteWithChildren
  '/$userId/upload': typeof UserIdUploadRoute
  '/$userId': typeof UserIdIndexRoute
  '/$userId/album/$albumId': typeof UserIdAlbumAlbumIdRoute
  '/$userId/profile/albums': typeof UserIdProfileAlbumsRoute
  '/$userId/profile/gallery': typeof UserIdProfileGalleryRoute
  '/$userId/profile/settings': typeof UserIdProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$userId': typeof UserIdRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/$userId/profile': typeof UserIdProfileRouteRouteWithChildren
  '/$userId/upload': typeof UserIdUploadRoute
  '/$userId/': typeof UserIdIndexRoute
  '/$userId/album/$albumId': typeof UserIdAlbumAlbumIdRoute
  '/$userId/profile/albums': typeof UserIdProfileAlbumsRoute
  '/$userId/profile/gallery': typeof UserIdProfileGalleryRoute
  '/$userId/profile/settings': typeof UserIdProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$userId'
    | '/signIn'
    | '/$userId/profile'
    | '/$userId/upload'
    | '/$userId/'
    | '/$userId/album/$albumId'
    | '/$userId/profile/albums'
    | '/$userId/profile/gallery'
    | '/$userId/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signIn'
    | '/$userId/profile'
    | '/$userId/upload'
    | '/$userId'
    | '/$userId/album/$albumId'
    | '/$userId/profile/albums'
    | '/$userId/profile/gallery'
    | '/$userId/profile/settings'
  id:
    | '__root__'
    | '/$userId'
    | '/signIn'
    | '/$userId/profile'
    | '/$userId/upload'
    | '/$userId/'
    | '/$userId/album/$albumId'
    | '/$userId/profile/albums'
    | '/$userId/profile/gallery'
    | '/$userId/profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserIdRouteRoute: typeof UserIdRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId': {
      id: '/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/'
      fullPath: '/$userId/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof UserIdRouteRoute
    }
    '/$userId/upload': {
      id: '/$userId/upload'
      path: '/upload'
      fullPath: '/$userId/upload'
      preLoaderRoute: typeof UserIdUploadRouteImport
      parentRoute: typeof UserIdRouteRoute
    }
    '/$userId/profile': {
      id: '/$userId/profile'
      path: '/profile'
      fullPath: '/$userId/profile'
      preLoaderRoute: typeof UserIdProfileRouteRouteImport
      parentRoute: typeof UserIdRouteRoute
    }
    '/$userId/profile/settings': {
      id: '/$userId/profile/settings'
      path: '/settings'
      fullPath: '/$userId/profile/settings'
      preLoaderRoute: typeof UserIdProfileSettingsRouteImport
      parentRoute: typeof UserIdProfileRouteRoute
    }
    '/$userId/profile/gallery': {
      id: '/$userId/profile/gallery'
      path: '/gallery'
      fullPath: '/$userId/profile/gallery'
      preLoaderRoute: typeof UserIdProfileGalleryRouteImport
      parentRoute: typeof UserIdProfileRouteRoute
    }
    '/$userId/profile/albums': {
      id: '/$userId/profile/albums'
      path: '/albums'
      fullPath: '/$userId/profile/albums'
      preLoaderRoute: typeof UserIdProfileAlbumsRouteImport
      parentRoute: typeof UserIdProfileRouteRoute
    }
    '/$userId/album/$albumId': {
      id: '/$userId/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/$userId/album/$albumId'
      preLoaderRoute: typeof UserIdAlbumAlbumIdRouteImport
      parentRoute: typeof UserIdRouteRoute
    }
  }
}

interface UserIdProfileRouteRouteChildren {
  UserIdProfileAlbumsRoute: typeof UserIdProfileAlbumsRoute
  UserIdProfileGalleryRoute: typeof UserIdProfileGalleryRoute
  UserIdProfileSettingsRoute: typeof UserIdProfileSettingsRoute
}

const UserIdProfileRouteRouteChildren: UserIdProfileRouteRouteChildren = {
  UserIdProfileAlbumsRoute: UserIdProfileAlbumsRoute,
  UserIdProfileGalleryRoute: UserIdProfileGalleryRoute,
  UserIdProfileSettingsRoute: UserIdProfileSettingsRoute,
}

const UserIdProfileRouteRouteWithChildren =
  UserIdProfileRouteRoute._addFileChildren(UserIdProfileRouteRouteChildren)

interface UserIdRouteRouteChildren {
  UserIdProfileRouteRoute: typeof UserIdProfileRouteRouteWithChildren
  UserIdUploadRoute: typeof UserIdUploadRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  UserIdAlbumAlbumIdRoute: typeof UserIdAlbumAlbumIdRoute
}

const UserIdRouteRouteChildren: UserIdRouteRouteChildren = {
  UserIdProfileRouteRoute: UserIdProfileRouteRouteWithChildren,
  UserIdUploadRoute: UserIdUploadRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  UserIdAlbumAlbumIdRoute: UserIdAlbumAlbumIdRoute,
}

const UserIdRouteRouteWithChildren = UserIdRouteRoute._addFileChildren(
  UserIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UserIdRouteRoute: UserIdRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
